---
- name: Setup ZCash zecminer
  hosts: miner
  become: true
  tasks:
    - name: Create zecminer user
      user:
        comment: ZCash zecminer daemon account
        name: zecminer
        group: zecminer
        state: present
    - name: Extract zecminer binaries
      unarchive:
        src: https://github.com/nanopool/ewbf-miner/releases/download/v0.3.4b/Zec.miner.0.3.4b.Linux.Bin.tar.gz
        dest: /opt/zecminer
        owner: zecminer
        group: zecminer
        mode: '0775'
        remote_src: yes
  roles:
    - role: 0x0i.systemd
      become: true
      vars:
        unit_config:
          - name: zecminer
            Unit:
              Description: Zcash cuda miner written for pascal GPUs
              Documentation: https://github.com/nanopool/ewbf-miner
              User: zecminer
              Group: zecminer
              WorkingDirectory: /opt/zecminer
              StandardOutput: journal
              StandardError: Inherit
            Service:
              ExecStart: /opt/zecminer/miner --config /opt/zecminer/miner.cfg
              ExecReload: /bin/kill -HUP $MAINPID
            Install:
              WantedBy: multi-user.target
